// <auto-generated />
namespace imgcrv.Presentation.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class crvPth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(crvPth));
        
        string IMigrationMetadata.Id
        {
            get { return "201405111346269_crvPth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
